# Generated by Django 5.2.6 on 2025-09-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_publicacion_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
    ]
