# Generated by Django 5.2.6 on 2025-09-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estrellas',
            field=models.IntegerField(default=0),
        ),
    ]
